# Search/Eureka Server Port (prod) : "배포설명" 확인

# Search Server Port
server:
  port: ${PORT_NUMBER}

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}


logging:
  level:
    root: info
