# Search/Eureka Server Port (prod) : "배포설명" 확인

# Search Server Port

server:
  port: ${PORT_NUMBER}

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}

spring:
  application:
    name: chaekmate-search

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID}
          location: asia-northeast1
          chat:
            options:
              model: gemini-2.5-flash
  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_RANGE:303}
rabbitmq:
  exchange:
    name: cm-book-exchange
  queues:
    queue-names:  cm-book-1
    routing-keys:  cm-book-key-1

ollama:
  api:
    url: ${OLLAMA_API_URL}

rerank:
  api:
    url: ${RERANK_API_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info
