# Search/Eureka Server Port (prod) : "배포설명" 확인

# Search Server Port
server:
  port: ${PORT_NUMBER}

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 309
rabbitmq:
  exchange:
    name: cm-book-exchange
  queues:
    - name: cm-book-1
      routing-key: cm-book-key-1
    - name: cm-book-2
      routing-key: cm-book-key-2
    - name: cm-book-3
      routing-key: cm-book-key-3

ollama:
  api:
    url: ${OLLAMA_API_URL}

logging:
  level:
    root: info